/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export declare function hello(name: string): string
export const enum Kind {
  Dog = 'Dog',
  Cat = 'Cat'
}
export declare class Animal {
  name: string
  age: number
  constructor(name: string, age: number)
  changeName(newName: string): void
}
