/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Kind {
  Dog = 'Dog',
  Cat = 'Cat'
}
export declare function coolFunction(kind: Kind): string
export declare function sum(a: number, b: number): number
export declare function hello(name: string): string
export declare function highOrderFunction(aArg: number, callback: (s: number)=>string): number
export declare function getEnv(env: string): string | null
export declare function sayA(s?: boolean | undefined | null): boolean
export declare function getSum(nums: Array<number>): number
export declare class Animal {
  name: string
  age: number
  constructor(name: string, age: number)
  changeName(newName: string): void
}
export declare class Dog {
  name: string
  constructor(name: string)
}
export declare class Cat {
  name: string
  constructor(name: string)
  static create(name: string): Cat
}
